name: Feature
labels: ["feature"]
body:
  - type: input
    id: goal
    attributes: { label: 목표, placeholder: 무엇을/왜 }
  - type: dropdown
    id: area
    attributes: { label: Area, options: [crypto_backtester, engine, strategies, scripts, db, reports, experiments] }
  - type: dropdown
    id: release
    attributes: { label: Release, options: [v0.1, v0.2, v0.3, v0.4, v0.5] }
  - type: dropdown
    id: priority
    attributes: { label: Priority, options: [P0, P1, P2, P3] }
  - type: textarea
    id: acceptance
    attributes: { label: 완료 기준(DoD), placeholder: 체크리스트로 명확히 }
